import { l } from "@/lib/excursions";

// Catalogue-only copy: shared navigation, guides and SEO remain unchanged.
export const catalogCopy = {
  more: l("Подробнее о маршруте", "Mai multe despre traseu", "Explore this route", "Докладніше про маршрут", "Více o trase"),
  external: l("Внешний гид · Moldova Travel", "Ghid extern · Moldova Travel", "External guide · Moldova Travel", "Зовнішній гід · Moldova Travel", "Externí průvodce · Moldova Travel"),
  intro: l("Расскажите о дате, числе гостей и удобном языке. Проверим возможность организации выбранного маршрута у исполнителя.", "Spune-ne data, numărul de oaspeți și limba preferată. Vom verifica la prestator dacă traseul ales poate fi organizat.", "Tell us your preferred date, guest count and language. We will check with the provider whether your chosen route can be arranged.", "Повідомте дату, кількість гостей і зручну мову. Перевіримо у виконавця можливість організації обраного маршруту.", "Napište nám termín, počet hostů a preferovaný jazyk. U poskytovatele ověříme možnost uspořádání vybrané trasy."),
  terms: l("Запрос не является подтверждённой бронью. Программа и цена согласуются отдельно; проведение возможно только после подтверждения исполнителем.", "Cererea nu este o rezervare confirmată. Programul și prețul se stabilesc separat; organizarea este posibilă numai după confirmarea prestatorului.", "An enquiry is not a confirmed booking. The itinerary and price are agreed separately; the trip is only possible once the provider confirms.", "Запит не є підтвердженим бронюванням. Програму й ціну узгоджуємо окремо; проведення можливе лише після підтвердження виконавцем.", "Dotaz není potvrzená rezervace. Program a cenu dohodneme zvlášť; výlet je možný až po potvrzení poskytovatelem."),
};

export const routeSummaries = {
  orhei: l("Скальные пейзажи долины Раута и сёла Бутучень и Требужень — для прогулок и знакомства с сельской Молдовой.", "Peisajele stâncoase ale Răutului și satele Butuceni și Trebujeni, pentru plimbări și descoperirea Moldovei rurale.", "Rocky Răut valley scenery and the villages of Butuceni and Trebujeni, for walks and a taste of rural Moldova.", "Скельні краєвиди долини Реута й села Бутучень і Требужень — для прогулянок і знайомства із сільською Молдовою.", "Skalnaté údolí Răutu a vesnice Butuceni a Trebujeni lákají k procházkám a poznávání moldavského venkova."),
  cricova: l("Подземные винные галереи рядом со столицей. Знакомство с виноделием без долгой поездки.", "Galerii vinicole subterane lângă capitală. Descoperă vinificația fără un drum lung.", "Underground wine galleries close to the capital. Discover winemaking without a long journey.", "Підземні винні галереї поруч зі столицею. Знайомство з виноробством без довгої поїздки.", "Podzemní vinné galerie blízko hlavního města. Poznejte vinařství bez dlouhé cesty."),
  milestii: l("Винные подземелья и коллекция бутылок к югу от Кишинёва. Маршрут для ценителей атмосферы старых галерей.", "Galerii vinicole și o colecție de sticle la sud de Chișinău. Un traseu pentru atmosfera vechilor beciuri.", "Wine cellars and a bottle collection south of Chisinau. A route for those drawn to the atmosphere of old galleries.", "Винні підземелля та колекція пляшок на південь від Кишинева. Маршрут для поціновувачів атмосфери старих галерей.", "Vinné sklepy a sbírka lahví jižně od Kišiněva. Trasa pro milovníky atmosféry starých galerií."),
  city: l("Соборный сквер, Триумфальная арка и остановка на местную кухню. Знакомство со столицей в пешем темпе.", "Parcul Catedralei, Arcul de Triumf și o oprire pentru bucătăria locală. Descoperă capitala la pas.", "Cathedral Park, the Triumphal Arch and a stop for local food. Discover the capital on foot.", "Сквер собору, Тріумфальна арка та зупинка на місцеву кухню. Знайомство зі столицею пішки.", "Park katedrály, Vítězný oblouk a zastávka na místní jídlo. Poznejte hlavní město pěšky."),
  combined: l("Пейзажи Старого Орхея, монастырь Курки и галереи Cricova — три разных впечатления за насыщенный день.", "Peisajele Orheiului Vechi, Mănăstirea Curchi și galeriile Cricova: trei experiențe într-o zi plină.", "Old Orhei scenery, Curchi Monastery and Cricova galleries: three different experiences in one full day.", "Краєвиди Старого Оргієва, монастир Куркі й галереї Cricova — три різні враження за насичений день.", "Krajina Starého Orhei, klášter Curchi a galerie Cricova: tři různé zážitky během nabitého dne."),
  gagauzia: l("Комрат и этнографический музей в Бешалме: знакомство с гагаузской культурой и традициями юга.", "Comrat și muzeul etnografic din Beșalma: descoperă cultura găgăuză și tradițiile sudului.", "Comrat and Beșalma's ethnographic museum: an introduction to Gagauz culture and southern traditions.", "Комрат та етнографічний музей у Бешалмі: знайомство з гагаузькою культурою й традиціями півдня.", "Comrat a etnografické muzeum v Beșalmě: seznámení s gagauzskou kulturou a tradicemi jihu."),
  soroca: l("Каменная крепость Сорока и берег Днестра. Поездка на север ради истории и речных пейзажей.", "Cetatea de piatră din Soroca și malul Nistrului. O călătorie spre nord pentru istorie și peisaje riverane.", "Soroca's stone fortress and the Dniester riverbank. Head north for history and river scenery.", "Кам’яна фортеця Сороки та берег Дністра. Поїздка на північ заради історії й річкових краєвидів.", "Kamenná pevnost Soroca a břeh Dněstru. Výlet na sever za historií a říční krajinou."),
  monasteries: l("Архитектура монастыря Курки и спокойная прогулка в окрестностях — маршрут без спешки.", "Arhitectura Mănăstirii Curchi și o plimbare liniștită în împrejurimi, fără grabă.", "Curchi Monastery's architecture and a quiet walk nearby, at an unhurried pace.", "Архітектура монастиря Куркі та спокійна прогулянка поблизу — маршрут без поспіху.", "Architektura kláštera Curchi a klidná procházka v okolí, beze spěchu."),
  mimi: l("Вино и архитектура комплекса Castel Mimi в Бульбоаке. Идея поездки для знакомства с винодельней.", "Vin și arhitectură la Castel Mimi, în Bulboaca. O idee de excursie pentru descoperirea vinăriei.", "Wine and the architecture of Castel Mimi in Bulboaca. A day-trip idea to discover the winery.", "Вино й архітектура комплексу Castel Mimi в Бульбоаці. Ідея поїздки для знайомства з виноробнею.", "Víno a architektura areálu Castel Mimi v Bulboace. Tip na výlet za poznáním vinařství."),
};
