import type { Language } from "@/locales/translations";

export const l = (ru: string, ro: string, en: string, uk: string, cs: string): Record<Language, string> => ({ ru, ro, en, uk, cs });

export const travelUi = {
  title: l("Экскурсии и маршруты по Молдове из Кишинёва", "Excursii și trasee prin Moldova din Chișinău", "Moldova tours and day trips from Chisinau", "Екскурсії та маршрути Молдовою з Кишинева", "Výlety a trasy po Moldavsku z Kišiněva"),
  intro: l("Подземные винные галереи, сёла над Рау́том и прогулки по столице. Выберите направление и узнайте, что стоит учесть перед поездкой.", "Galerii vinicole subterane, sate deasupra Răutului și plimbări prin capitală. Alege o destinație și află ce să verifici înainte de plecare.", "Underground wine galleries, villages above the Răut and walks through the capital. Choose a destination and find out what to check before setting out.", "Підземні винні галереї, села над Реутом і прогулянки столицею. Оберіть напрямок і дізнайтеся, що врахувати перед поїздкою.", "Podzemní vinné galerie, vesnice nad řekou Răut a procházky hlavním městem. Vyberte si cíl a zjistěte, co ověřit před cestou."),
  navTitle: l("Экскурсии по Молдове", "Excursii prin Moldova", "Explore Moldova", "Екскурсії Молдовою", "Výlety po Moldavsku"),
  navText: l("Маршруты из Кишинёва: вино, история и природа", "Trasee din Chișinău: vin, istorie și natură", "Routes from Chisinau: wine, history and nature", "Маршрути з Кишинева: вино, історія та природа", "Trasy z Kišiněva: víno, historie a příroda"),
  all: l("Все направления", "Toate destinațiile", "All destinations", "Усі напрямки", "Všechny cíle"),
  wine: l("Вино", "Vin", "Wine", "Вино", "Víno"),
  history: l("История", "Istorie", "History", "Історія", "Historie"),
  city: l("Город и кухня", "Oraș și gastronomie", "City and food", "Місто та кухня", "Město a gastronomie"),
  nature: l("Природа", "Natură", "Nature", "Природа", "Příroda"),
  culture: l("Культура", "Cultură", "Culture", "Культура", "Kultura"),
  half: l("На полдня", "O jumătate de zi", "Half a day", "На пів дня", "Na půl dne"),
  day: l("На день", "O zi", "A full day", "На день", "Na celý den"),
  durationNote: l("Длительность — ориентир для планирования с выездом из Кишинёва и возвращением, а не расписание тура. Она зависит от транспорта, остановок и подтверждённого времени визита.", "Durata este orientativă pentru plecarea din Chișinău și întoarcere, nu un orar de tur. Depinde de transport, opriri și ora confirmată a vizitei.", "Durations are planning estimates including departure from and return to Chisinau, not tour schedules. Allow for your transport, stops and confirmed visit times.", "Тривалість — орієнтир для планування з виїздом із Кишинева та поверненням, а не розклад туру. Вона залежить від транспорту, зупинок і підтвердженого часу візиту.", "Délka je orientační a zahrnuje cestu z Kišiněva a zpět, nejde o jízdní řád výletu. Záleží na dopravě, zastávkách a potvrzeném čase návštěvy."),
  before: l("Перед поездкой", "Înainte de plecare", "Before you go", "Перед поїздкою", "Před cestou"),
  guide: l("Читать путеводитель", "Citește ghidul", "Read the guide", "Читати путівник", "Přečíst průvodce"),
  source: l("Информация о направлении", "Informații despre destinație", "Destination information", "Інформація про напрямок", "Informace o cíli"),
  plan: l("Помочь с организацией?", "Ai nevoie de ajutor cu organizarea?", "Need help planning a visit?", "Допомогти з організацією?", "Potřebujete pomoc s plánováním?"),
  requestNote: l("Программу составляем по запросу и только после подтверждения исполнителем. RentPlaceMD не владеет винодельнями и не гарантирует проведение всех маршрутов. Сначала уточним доступность гида, транспорт, язык, состав программы и цену. Отправка запроса не является бронированием.", "Programul se alcătuiește la cerere și numai după confirmarea prestatorului. RentPlaceMD nu deține vinării și nu garantează organizarea tuturor traseelor. Verificăm mai întâi ghidul, transportul, limba, programul și prețul. Trimiterea cererii nu constituie o rezervare.", "Programs are arranged on request and only after the provider confirms. RentPlaceMD does not own wineries or guarantee that every route can be organised. We first check the guide, transport, language, itinerary and price. Sending an enquiry is not a booking.", "Програму складаємо на запит і лише після підтвердження виконавцем. RentPlaceMD не володіє виноробнями та не гарантує проведення всіх маршрутів. Спочатку уточнимо гіда, транспорт, мову, програму й ціну. Надсилання запиту не є бронюванням.", "Program připravujeme na vyžádání a až po potvrzení poskytovatelem. RentPlaceMD nevlastní vinařství ani nezaručuje realizaci všech tras. Nejprve ověříme průvodce, dopravu, jazyk, program a cenu. Odeslání dotazu není rezervace."),
  request: l("Узнать программу и цену", "Solicită programul și prețul", "Ask about the itinerary and price", "Дізнатися програму й ціну", "Zeptat se na program a cenu"),
  onRequest: l("По запросу, после подтверждения", "La cerere, după confirmare", "On request, subject to confirmation", "На запит, після підтвердження", "Na vyžádání, po potvrzení"),
  route: l("Маршрут", "Traseu", "Route", "Маршрут", "Trasa"),
  date: l("Желаемая дата", "Data dorită", "Preferred date", "Бажана дата", "Preferované datum"),
  guests: l("Число гостей", "Număr de oaspeți", "Number of guests", "Кількість гостей", "Počet hostů"),
  language: l("Язык экскурсии", "Limba excursiei", "Tour language", "Мова екскурсії", "Jazyk prohlídky"),
  unspecified: l("Уточним в переписке", "De stabilit în conversație", "To discuss in the chat", "Уточнимо в листуванні", "Upřesníme ve zprávách"),
  stayTitle: l("Кишинёв — ваша база для поездок", "Chișinău — baza ta pentru excursii", "Make Chisinau your base", "Кишинів — ваша база для поїздок", "Kišiněv jako základna pro výlety"),
  stayText: l("Оставьте время на сам город. Между поездками удобно вернуться в свою квартиру, приготовить завтрак и спланировать следующий день. В каталоге RentPlaceMD можно выбрать жильё под число гостей и район.", "Păstrează timp și pentru oraș. Între excursii te poți întoarce în apartament, pregăti micul dejun și planifica ziua următoare. În catalogul RentPlaceMD alegi cazarea după numărul de oaspeți și zonă.", "Leave time for the city itself. Between trips, return to your apartment, prepare breakfast and plan the next day. Browse RentPlaceMD accommodation by guest count and neighbourhood.", "Залиште час і на саме місто. Між поїздками зручно повернутися у свою квартиру, приготувати сніданок і спланувати наступний день. У каталозі RentPlaceMD можна обрати житло за кількістю гостей і районом.", "Nechte si čas i na samotné město. Mezi výlety se můžete vrátit do apartmánu, připravit snídani a naplánovat další den. V katalogu RentPlaceMD vyberete ubytování podle počtu hostů a čtvrti."),
  apartments: l("Выбрать квартиру", "Alege un apartament", "Find an apartment", "Обрати квартиру", "Vybrat apartmán"),
  hub: l("Общий путеводитель", "Ghid general", "Travel guide", "Загальний путівник", "Cestovní průvodce"),
  events: l("Календарь событий", "Calendar de evenimente", "Events calendar", "Календар подій", "Kalendář akcí"),
  transfer: l("Трансфер", "Transfer", "Transfer", "Трансфер", "Transfer"),
  photos: l("Фотографии и лицензии", "Fotografii și licențe", "Photos and licences", "Фотографії та ліцензії", "Fotografie a licence"),
  creditsNote: l("Локальные копии: кадрирование, уменьшение и WebP. Фото виноградника показывает Cricova, а не другие винодельни.", "Copii locale: decupare, redimensionare și WebP. Fotografia podgoriei reprezintă Cricova, nu alte vinării.", "Local copies: cropped, resized and converted to WebP. The vineyard photograph shows Cricova, not other wineries.", "Локальні копії: кадрування, зменшення та WebP. Фото виноградника показує Cricova, а не інші виноробні.", "Místní kopie: ořez, zmenšení a převod do WebP. Fotografie vinice zobrazuje Cricovu, nikoli jiná vinařství."),
};

export type Theme = "wine" | "history" | "city" | "nature" | "culture";
export type Excursion = { id: string; number: string; title: Record<Language, string>; description: Record<Language, string>; tip: Record<Language, string>; duration: "half" | "day"; themes: Theme[]; href: string; external?: boolean; image?: string; requestable?: boolean };
const outdoor = l("Весной и осенью удобнее гулять; летом возьмите воду и защиту от солнца. После дождя тропы могут быть скользкими. Уточните доступ к объектам и выберите обувь для неровного рельефа.", "Primăvara și toamna sunt potrivite pentru plimbări; vara ia apă și protecție solară. După ploaie potecile pot fi alunecoase. Verifică accesul și alege încălțăminte pentru teren denivelat.", "Spring and autumn suit walking; in summer bring water and sun protection. Trails may be slippery after rain. Check site access and wear shoes suitable for uneven ground.", "Навесні й восени зручніше гуляти; влітку візьміть воду та захист від сонця. Після дощу стежки можуть бути слизькими. Уточніть доступ і оберіть взуття для нерівного рельєфу.", "Na procházky se hodí jaro a podzim; v létě vezměte vodu a ochranu před sluncem. Po dešti mohou stezky klouzat. Ověřte přístup a zvolte boty do nerovného terénu.");
const cellar = l("В прохладные галереи возьмите дополнительный слой одежды даже летом. Заранее подтвердите время, язык, транспорт внутри комплекса и состав дегустации; после вина не планируйте вести машину.", "Ia un strat suplimentar de haine pentru galeriile răcoroase, chiar și vara. Confirmă ora, limba, transportul în complex și degustarea; nu planifica să conduci după consumul de vin.", "Bring an extra layer for the cool galleries, even in summer. Confirm the time, language, transport inside the complex and tasting inclusions; do not plan to drive after drinking wine.", "Для прохолодних галерей візьміть додатковий шар одягу навіть улітку. Підтвердьте час, мову, транспорт усередині комплексу та склад дегустації; після вина не плануйте керувати авто.", "Do chladných galerií vezměte další vrstvu oblečení i v létě. Potvrďte čas, jazyk, dopravu uvnitř areálu a obsah degustace; po víně neplánujte řídit.");

export const excursions: Excursion[] = [
  { id: "orhei", number: "01", title: l("Старый Орхей", "Orheiul Vechi", "Old Orhei", "Старий Оргіїв", "Starý Orhei"), duration: "day", themes: ["history", "nature"], image: "/guide/moldova-trips.webp", href: "/guide/orheiul-vechi", requestable: true,
    description: l("Долина Раута, скальные пейзажи и сёла Бутучень и Требужень. Совместите прогулку с знакомством с сельской архитектурой; обед в гостевом доме согласуйте отдельно.", "Valea Răutului, peisaje stâncoase și satele Butuceni și Trebujeni. Combină plimbarea cu arhitectura rurală; stabilește separat prânzul la o pensiune.", "Explore the Răut valley, rocky scenery and the villages of Butuceni and Trebujeni. Combine a walk with village architecture; arrange any guesthouse lunch separately.", "Долина Реута, скельні краєвиди та села Бутучень і Требужень. Поєднайте прогулянку із сільською архітектурою; обід у гостьовому будинку узгодьте окремо.", "Údolí Răutu, skalnatá krajina a vesnice Butuceni a Trebujeni. Spojte procházku s venkovskou architekturou; oběd v penzionu domluvte zvlášť."), tip: outdoor },
  { id: "cricova", number: "02", title: l("Крикова", "Cricova", "Cricova", "Крикова", "Cricova"), duration: "half", themes: ["wine"], image: "/guide/wineries.webp", href: "/guide/wineries/cricova", requestable: true,
    description: l("Подземные винные галереи рядом со столицей. Подойдёт для знакомства с виноделием без насыщенного дня в дороге; экскурсия и дегустация зависят от выбранной программы.", "Galerii vinicole subterane lângă capitală. O introducere în vinificație fără o zi încărcată pe drum; vizita și degustarea depind de programul ales.", "Underground wine galleries close to the capital. An introduction to winemaking without a long day on the road; the tour and tasting depend on your chosen program.", "Підземні винні галереї поруч зі столицею. Знайомство з виноробством без насиченого дня в дорозі; екскурсія та дегустація залежать від обраної програми.", "Podzemní vinné galerie blízko hlavního města. Seznámení s vinařstvím bez dlouhého dne na cestě; prohlídka a degustace závisí na zvoleném programu."), tip: cellar },
  { id: "milestii", number: "03", title: l("Милештий Мичь", "Mileștii Mici", "Mileștii Mici", "Мілештій Мічь", "Mileștii Mici"), duration: "half", themes: ["wine"], href: "/guide/wineries/milestii-mici", requestable: true,
    description: l("Винные подземелья и коллекция бутылок к югу от Кишинёва. Выберите этот маршрут, если интересны хранение вина и атмосфера галерей; детали посещения согласуйте с винодельней.", "Galerii subterane și o colecție de sticle la sud de Chișinău. Alege traseul pentru păstrarea vinului și atmosfera galeriilor; stabilește detaliile vizitei cu vinăria.", "Wine cellars and a bottle collection south of Chisinau. Choose this route for wine storage and the atmosphere of the galleries; confirm visit details with the winery.", "Винні підземелля та колекція пляшок на південь від Кишинева. Оберіть маршрут, якщо цікавить зберігання вина й атмосфера галерей; деталі узгодьте з виноробнею.", "Vinné sklepy a sbírka lahví jižně od Kišiněva. Trasa pro zájemce o uchovávání vína a atmosféru galerií; podrobnosti návštěvy domluvte s vinařstvím."), tip: cellar },
  { id: "city", number: "04", title: l("Кишинёв: прогулка и кухня", "Chișinău: plimbări și gastronomie", "Chisinau walks and local food", "Кишинів: прогулянки та гастрономія", "Kišiněv: procházky a gastronomie"), duration: "half", themes: ["city", "culture"], image: "/guide/walking-tours.webp", href: "/guide/walking-tours",
    description: l("Начните с центра, соборного сквера и Триумфальной арки, затем сделайте остановку на местную кухню. Пеший маршрут легко разделить на короткие прогулки.", "Începe cu centrul, Parcul Catedralei și Arcul de Triumf, apoi oprește-te pentru bucătăria locală. Traseul pietonal poate fi împărțit în plimbări scurte.", "Start in the centre with Cathedral Park and the Triumphal Arch, then stop for local food. Split the walk into shorter outings if you prefer a slower pace.", "Почніть із центру, скверу собору та Тріумфальної арки, потім зупиніться скуштувати місцеву кухню. Піший маршрут легко розділити на короткі прогулянки.", "Začněte v centru u parku katedrály a Vítězného oblouku a pak se zastavte na místní jídlo. Pěší trasu lze rozdělit na kratší procházky."),
    tip: l("Летом гуляйте утром или ближе к вечеру; зимой добавьте музей или кафе. Уточните часы работы, доступность столика и пищевые ограничения.", "Vara plimbă-te dimineața sau spre seară; iarna adaugă un muzeu sau o cafenea. Verifică orarul, disponibilitatea unei mese și restricțiile alimentare.", "In summer walk in the morning or towards evening; in winter add a museum or café. Check opening hours, table availability and dietary requirements.", "Улітку гуляйте вранці або ближче до вечора; взимку додайте музей чи кафе. Уточніть години роботи, наявність столика й харчові обмеження.", "V létě vyrazte ráno nebo k večeru; v zimě přidejte muzeum či kavárnu. Ověřte otevírací dobu, volný stůl a dietní požadavky.") },
  { id: "combined", number: "05", title: l("Старый Орхей — Курки — Крикова", "Orheiul Vechi — Curchi — Cricova", "Old Orhei — Curchi — Cricova", "Старий Оргіїв — Куркі — Крикова", "Starý Orhei — Curchi — Cricova"), duration: "day", themes: ["history", "wine", "nature"], href: "/guide/orheiul-vechi", requestable: true,
    description: l("Идея насыщенного дня: пейзажи Старого Орхея, монастырь Курки и винные галереи Cricova. Порядок остановок определяется подтверждённым временем визита на винодельню.", "Idee pentru o zi plină: peisajele Orheiului Vechi, Mănăstirea Curchi și galeriile Cricova. Ordinea opririlor depinde de ora confirmată la vinărie.", "An ambitious day combining Old Orhei scenery, Curchi Monastery and Cricova wine galleries. The order of stops depends on the winery's confirmed visiting slot.", "Ідея насиченого дня: краєвиди Старого Оргієва, монастир Куркі та галереї Cricova. Порядок зупинок залежить від підтвердженого часу візиту на виноробню.", "Nápad na nabitý den: krajina Starého Orhei, klášter Curchi a galerie Cricova. Pořadí zastávek závisí na potvrzeném čase ve vinařství."),
    tip: l("В короткий зимний день лучше сократить маршрут. Уточните часы доступа в монастырь, одежду для посещения и время на обед; если хотите спокойный темп, разделите поездку на два дня.", "În zilele scurte de iarnă este mai bine să scurtezi traseul. Verifică accesul la mănăstire, ținuta și timpul pentru prânz; pentru un ritm liniștit, împarte excursia în două zile.", "Shorten the route on short winter days. Check monastery access, appropriate clothing and time for lunch; for a relaxed pace, split the trip over two days.", "У короткий зимовий день краще скоротити маршрут. Уточніть доступ до монастиря, одяг для відвідування й час на обід; для спокійного темпу розділіть поїздку на два дні.", "V krátkých zimních dnech trasu zkraťte. Ověřte přístup do kláštera, vhodné oblečení a čas na oběd; pro klidnější tempo rozdělte cestu do dvou dnů.") },
  { id: "gagauzia", number: "06", title: l("Гагаузия: Комрат и Бешалма", "Găgăuzia: Comrat și Beșalma", "Gagauzia: Comrat and Beșalma", "Гагаузія: Комрат і Бешалма", "Gagauzsko: Comrat a Beșalma"), duration: "day", themes: ["culture", "city"], href: "/guide/gagauzia",
    description: l("Знакомство с гагаузской культурой на юге Молдовы: Комрат и этнографический музей в Бешалме. Встречу с местной кухней планируйте как отдельную остановку.", "Descoperă cultura găgăuză în sudul Moldovei: Comrat și muzeul etnografic din Beșalma. Planifică separat o oprire pentru bucătăria locală.", "Discover Gagauz culture in southern Moldova through Comrat and the ethnographic museum in Beșalma. Plan a separate stop to try local food.", "Знайомство з гагаузькою культурою на півдні Молдови: Комрат та етнографічний музей у Бешалмі. Місцеву кухню заплануйте як окрему зупинку.", "Poznejte gagauzskou kulturu na jihu Moldavska: Comrat a etnografické muzeum v Beșalmě. Na místní kuchyni si naplánujte samostatnou zastávku."),
    tip: l("Летом учитывайте жару, зимой — короткий световой день. До выезда подтвердите работу музея, язык сопровождения и место обеда; не рассчитывайте на посещение без согласования.", "Vara ține cont de căldură, iarna de ziua scurtă. Confirmă muzeul, limba ghidului și locul pentru prânz înainte de plecare; nu conta pe o vizită neanunțată.", "Allow for summer heat and short winter daylight. Confirm museum access, guiding language and lunch before leaving; do not rely on an unannounced visit.", "Улітку враховуйте спеку, взимку — короткий день. До виїзду підтвердьте роботу музею, мову супроводу та місце обіду; не розраховуйте на візит без узгодження.", "Počítejte s letním horkem a krátkým zimním dnem. Před cestou potvrďte návštěvu muzea, jazyk průvodce a oběd; nespoléhejte na návštěvu bez domluvy.") },
  { id: "soroca", number: "07", title: l("Сорока и Днестр", "Soroca și Nistrul", "Soroca and the Dniester", "Сороки та Дністер", "Soroca a Dněstr"), duration: "day", themes: ["history", "culture"], href: "/guide/soroca",
    description: l("Поездка на север к каменной крепости Сорока и берегу Днестра. Оставьте большую часть дня для этого направления, без попытки совместить его с югом страны.", "O călătorie spre nord, la cetatea de piatră din Soroca și malul Nistrului. Rezervă cea mai mare parte a zilei pentru această destinație, fără a o combina cu sudul țării.", "Head north to Soroca's stone fortress and the Dniester riverbank. Reserve most of the day for this destination instead of trying to combine it with southern Moldova.", "Поїздка на північ до кам’яної фортеці Сороки та берега Дністра. Залиште більшу частину дня для цього напрямку, не поєднуючи його з півднем країни.", "Vydejte se na sever ke kamenné pevnosti Soroca a břehu Dněstru. Vyhraďte si většinu dne a nespojujte výlet s jihem země."), tip: outdoor },
  { id: "monasteries", number: "08", title: l("Курки: монастырь и природа", "Mănăstiri și natură: Curchi", "Monasteries and nature: Curchi", "Монастирі та природа: Куркі", "Kláštery a příroda: Curchi"), duration: "half", themes: ["nature", "history"], image: "/guide/monasteries.webp", href: "/guide/monasteries",
    description: l("Архитектура монастыря Курки и спокойная прогулка в окрестностях. Это действующее религиозное место: стройте маршрут с уважением к богослужениям и правилам посещения.", "Arhitectura Mănăstirii Curchi și o plimbare liniștită în împrejurimi. Este un loc religios activ: respectă slujbele și regulile de vizitare.", "See Curchi Monastery's architecture and take a quiet walk nearby. This is an active religious site: respect services and visiting rules when planning your stop.", "Архітектура монастиря Куркі та спокійна прогулянка поблизу. Це діюче релігійне місце: поважайте богослужіння та правила відвідування.", "Architektura kláštera Curchi a klidná procházka v okolí. Jde o fungující náboženské místo: při plánování respektujte bohoslužby a pravidla návštěvy."), tip: outdoor },
  { id: "mimi", number: "09", title: l("Castel Mimi: вино и архитектура", "Castel Mimi: vin și arhitectură", "Castel Mimi: wine and architecture", "Castel Mimi: вино та архітектура", "Castel Mimi: víno a architektura"), duration: "day", themes: ["wine", "culture"], href: "/guide/wineries/castel-mimi",
    description: l("Винодельня в Бульбоаке для тех, кто хочет объединить знакомство с вином и архитектурой комплекса. Организация поездки и программа пока не подтверждены.", "Vinăria din Bulboaca pentru cei care vor să combine vinul cu arhitectura complexului. Organizarea călătoriei și programul nu sunt încă confirmate.", "The winery in Bulboaca combines wine with the architecture of its estate. Trip organisation and programme are not confirmed.", "Виноробня в Бульбоаці для тих, хто хоче поєднати вино з архітектурою комплексу. Організацію поїздки й програму поки не підтверджено.", "Vinařství v Bulboace spojuje víno s architekturou areálu. Organizace cesty a program nejsou potvrzeny."),
    tip: l("В тёплый сезон оставьте время на открытые пространства, в холодный уточните доступные помещения. Подтвердите экскурсию, дегустацию и ресторан отдельно.", "În sezonul cald rezervă timp pentru exterior, în cel rece verifică spațiile interioare disponibile. Confirmă separat turul, degustarea și restaurantul.", "Allow time outdoors in warm weather; in colder months check which indoor spaces are accessible. Confirm the tour, tasting and restaurant separately.", "У теплий сезон залиште час на відкриті простори, у холодний уточніть доступні приміщення. Підтвердьте екскурсію, дегустацію та ресторан окремо.", "Za tepla si nechte čas na venkovní prostory; v chladných měsících ověřte přístupné interiéry. Prohlídku, degustaci a restauraci potvrďte zvlášť.") },
];

export const carUi = {
  title: l("Аренда автомобиля", "Închiriere auto", "Car rental", "Оренда автомобіля", "Pronájem auta"),
  status: l("Готовим услугу", "Pregătim serviciul", "Service in preparation", "Готуємо послугу", "Službu připravujeme"),
  description: l("Аренда автомобиля для гостей RentPlaceMD готовится. Пока автомобиля для сдачи нет и бронирование недоступно. Для поездки посмотрите трансфер и маршруты по Молдове.", "Pregătim închirierea auto pentru oaspeții RentPlaceMD. Nu avem încă un automobil de închiriat, iar rezervarea nu este disponibilă. Descoperă transferul și traseele prin Moldova.", "Car rental for RentPlaceMD guests is being prepared. We do not yet have a car to rent and bookings are unavailable. Explore our transfer page and Moldova travel routes.", "Оренда автомобіля для гостей RentPlaceMD готується. Поки автомобіля для оренди немає й бронювання недоступне. Перегляньте трансфер і маршрути Молдовою.", "Pronájem auta pro hosty RentPlaceMD připravujeme. Zatím nemáme vůz k pronájmu a rezervace nejsou dostupné. Prohlédněte si transfer a trasy po Moldavsku."),
  later: l("Когда появится реальный автомобиль, здесь будут его фотографии, проверенные условия, стоимость, требования к водителю и правила страхования. Дата запуска пока не определена.", "Când vom avea un automobil real, aici vor apărea fotografiile, condițiile verificate, prețul, cerințele pentru șofer și regulile de asigurare. Data lansării nu este încă stabilită.", "Once a real vehicle is available, this page will show its photos, verified terms, price, driver requirements and insurance details. A launch date has not been set.", "Коли з’явиться реальний автомобіль, тут будуть його фотографії, перевірені умови, вартість, вимоги до водія та правила страхування. Дату запуску поки не визначено.", "Až bude skutečný vůz k dispozici, najdete zde fotografie, ověřené podmínky, cenu, požadavky na řidiče a pojištění. Termín spuštění zatím není stanoven."),
};

// Permanent identifiers are stored on routes, never derived from display order.
export const excursionLabel = (route: Excursion, language: Language) => `№ ${route.number} — ${route.title[language]}`;
