import { l } from "@/lib/excursions";

export const regionalGuideSlugs = ["gagauzia", "soroca"] as const;
export type RegionalGuideSlug = (typeof regionalGuideSlugs)[number];
export const isRegionalGuideSlug = (slug: string): slug is RegionalGuideSlug => regionalGuideSlugs.includes(slug as RegionalGuideSlug);
type Text = ReturnType<typeof l>;
type Section = { title: Text; body: Text };
type RegionalGuide = { title: Text; description: Text; intro: Text; stops: string[]; sections: Section[]; related: string };

export const regionalUi = {
  plan: l("План самостоятельной поездки", "Plan pentru o călătorie independentă", "Plan an independent visit", "План самостійної поїздки", "Plán samostatného výletu"),
  source: l("Проверить информацию у туристического источника", "Verifică informațiile la sursa turistică", "Check the tourism source", "Перевірити інформацію в туристичному джерелі", "Ověřit informace u turistického zdroje"),
  note: l("Это информационный маршрут, а не предложение готового тура. Часы работы, доступ в музеи и транспорт уточняйте перед выездом. Источник проверен 26 сентября 2026 года.", "Acesta este un traseu informativ, nu o ofertă de tur organizat. Verifică orarul, accesul la muzee și transportul înainte de plecare. Sursa a fost verificată pe 26 septembrie 2026.", "This is an informational route, not a ready-made tour offer. Confirm opening hours, museum access and transport before leaving. Source checked on 26 September 2026.", "Це інформаційний маршрут, а не пропозиція готового туру. Години роботи, доступ до музеїв і транспорт уточнюйте перед виїздом. Джерело перевірено 26 вересня 2026 року.", "Jde o informační trasu, nikoli nabídku hotového zájezdu. Před cestou ověřte otevírací dobu, přístup do muzeí a dopravu. Zdroj ověřen 26. září 2026."),
  related: l("Ещё один маршрут", "Încă un traseu", "Another route to explore", "Ще один маршрут", "Další tip na výlet"),
};

export const regionalGuides: Record<RegionalGuideSlug, RegionalGuide> = {
  gagauzia: {
    title: l("Гагаузия из Кишинёва: Комрат и Бешалма", "Găgăuzia din Chișinău: Comrat și Beșalma", "Gagauzia from Chisinau: Comrat and Beșalma", "Гагаузія з Кишинева: Комрат і Бешалма", "Z Kišiněva do Gagauzska: Comrat a Beșalma"),
    description: l("Самостоятельная поездка в Гагаузию: Комрат, музей в Бешалме, местная кухня, транспорт из Кишинёва и подготовка к дню на юге Молдовы.", "O călătorie independentă în Găgăuzia: Comrat, muzeul din Beșalma, bucătărie locală, transport din Chișinău și pregătirea unei zile în sudul Moldovei.", "Plan an independent Gagauzia day trip: Comrat, the museum in Beșalma, local food, transport from Chisinau and practical preparations for southern Moldova.", "Самостійна поїздка до Гагаузії: Комрат, музей у Бешалмі, місцева кухня, транспорт із Кишинева та підготовка до дня на півдні Молдови.", "Samostatný výlet do Gagauzska: Comrat, muzeum v Beșalmě, místní kuchyně, doprava z Kišiněva a příprava na den v jižním Moldavsku."),
    intro: l("За этой поездкой стоит ехать ради живой культуры, а не списка достопримечательностей. Уделите внимание музейным историям и местной кухне: такой день помогает увидеть другую сторону Молдовы за пределами столицы и винных галерей.", "Merită să vii pentru cultura vie, nu pentru o listă de obiective. Acordă timp poveștilor din muzeu și bucătăriei locale: această zi îți arată o altă latură a Moldovei, dincolo de capitală și galeriile vinicole.", "Come for living culture rather than a checklist of sights. Give time to museum stories and local food: this day offers another side of Moldova beyond the capital and wine galleries.", "Сюди варто їхати заради живої культури, а не переліку пам’яток. Приділіть увагу музейним історіям і місцевій кухні: такий день відкриває інший бік Молдови за межами столиці та винних галерей.", "Vydejte se sem za živou kulturou, nikoli seznamem památek. Věnujte čas muzejním příběhům a místní kuchyni: poznáte jinou stránku Moldavska než hlavní město a vinné galerie."),
    stops: ["Chișinău", "Comrat", "Beșalma", "Chișinău"],
    related: "soroca",
    sections: [
      { title: l("Что увидеть: город и музей", "Ce să vezi: orașul și muzeul", "What to see: town and museum", "Що побачити: місто й музей", "Co navštívit: město a muzeum"), body: l("Комрат можно сделать городской остановкой, а музей истории и этнографии в Бешалме — главным содержательным визитом. В музейном собрании представлены одежда, украшения, орудия труда и предметы быта. Сопровождение помогает понять назначение вещей: спросите заранее, возможен ли рассказ на нужном вам языке.", "Comrat poate fi oprirea urbană, iar muzeul de istorie și etnografie din Beșalma, vizita principală. Colecția include costume, bijuterii, unelte și obiecte casnice. Un ghid ajută la înțelegerea lor: întreabă din timp dacă explicațiile sunt disponibile în limba dorită.", "Use Comrat as your town stop and the history and ethnography museum in Beșalma as the main cultural visit. Its collection includes clothing, jewellery, tools and household objects. A guide can explain their purpose; ask ahead whether explanations are available in your preferred language.", "Комрат можна зробити міською зупинкою, а музей історії та етнографії в Бешалмі — головним змістовним візитом. У колекції є одяг, прикраси, знаряддя праці та предмети побуту. Супровід допомагає зрозуміти їхнє призначення: заздалегідь запитайте про потрібну мову.", "Comrat zvolte jako městskou zastávku a historické a etnografické muzeum v Beșalmě jako hlavní kulturní návštěvu. Sbírka zahrnuje oděvy, šperky, nástroje a předměty denní potřeby. Průvodce vysvětlí jejich účel; předem se zeptejte na výklad ve vašem jazyce.") },
      { title: l("Сколько времени заложить", "Cât timp să rezervi", "How much time to allow", "Скільки часу запланувати", "Kolik času si vyhradit"), body: l("Планируйте отдельный день с возвращением в Кишинёв. Это ориентир, а не длительность готовой экскурсии. Сначала закрепите время музея, затем распределите прогулку по Комрату и обед. Если едете общественным транспортом, разумнее сократить программу, чем зависеть от последнего обратного рейса.", "Rezervă o zi separată cu întoarcere la Chișinău. Este un reper, nu durata unui tur organizat. Stabilește mai întâi ora muzeului, apoi plimbarea prin Comrat și prânzul. Cu transportul public, mai bine reduci programul decât să depinzi de ultima cursă de întoarcere.", "Set aside a separate day returning to Chisinau. This is a planning allowance, not a scheduled tour duration. Fix the museum visit first, then fit in Comrat and lunch. With public transport, a shorter itinerary is wiser than depending on the last return service.", "Заплануйте окремий день із поверненням до Кишинева. Це орієнтир, а не тривалість готової екскурсії. Спершу узгодьте музей, потім прогулянку Комратом та обід. Із громадським транспортом краще скоротити програму, ніж залежати від останнього зворотного рейсу.", "Vyhraďte si samostatný den s návratem do Kišiněva. Jde o plánovací odhad, nikoli délku organizovaného výletu. Nejprve domluvte muzeum a potom procházku Comratem a oběd. Při veřejné dopravě je lepší kratší program než závislost na posledním zpátečním spoji.") },
      { title: l("Как добраться из Кишинёва", "Cum ajungi din Chișinău", "Getting there from Chisinau", "Як дістатися з Кишинева", "Jak se dostat z Kišiněva"), body: l("Для двух остановок практичнее заранее согласовать автомобиль с водителем и обратный путь. Уточните, входит ли ожидание у музея в договорённость. При самостоятельной поездке на автобусе сначала проверьте у перевозчика отправление в Комрат, затем отдельно транспорт до Бешалмы и обратно. Не считайте эти участки одним гарантированным сообщением.", "Pentru două opriri este mai practic să stabilești din timp o mașină cu șofer și întoarcerea. Întreabă dacă așteptarea la muzeu este inclusă. Cu autobuzul, verifică la transportator plecarea spre Comrat, apoi separat legătura spre Beșalma și înapoi. Nu presupune că toate segmentele formează o conexiune garantată.", "For two stops, consider arranging a car with a driver and the return journey in advance. Ask whether waiting at the museum is included. If travelling by bus, confirm the Comrat departure with the operator, then separately check onward transport to Beșalma and back. Do not assume those legs form one guaranteed connection.", "Для двох зупинок практичніше заздалегідь узгодити автомобіль із водієм і повернення. Уточніть, чи входить очікування біля музею. Якщо їдете автобусом, перевірте у перевізника відправлення до Комрата, потім окремо транспорт до Бешалми й назад. Не вважайте ці ділянки одним гарантованим сполученням.", "Pro dvě zastávky zvažte předem domluvené auto s řidičem i zpáteční cestu. Zeptejte se, zda je zahrnuto čekání u muzea. U autobusu ověřte u dopravce odjezd do Comratu a zvlášť spojení do Beșalmy a zpět. Nepředpokládejte, že tyto úseky tvoří jeden zaručený přípoj.") },
      { title: l("Обед как часть знакомства", "Prânzul ca parte a experienței", "Make lunch part of the visit", "Обід як частина знайомства", "Oběd jako součást poznávání"), body: l("Заложите спокойный обед вместо перекуса на ходу. Попросите принимающую сторону объяснить местные блюда, состав и размер порций; сообщите об аллергиях и ограничениях питания. Кулинарную встречу или домашний обед нужно договаривать отдельно — наличие музея в маршруте не означает, что питание уже организовано.", "Rezervă timp pentru un prânz liniștit. Roagă gazdele să explice preparatele locale, ingredientele și porțiile; anunță alergiile și restricțiile alimentare. O întâlnire culinară sau o masă acasă se stabilește separat: vizita la muzeu nu înseamnă că masa este deja organizată.", "Allow time for an unhurried lunch. Ask your host to explain local dishes, ingredients and portion sizes, and mention allergies or dietary needs. A cooking visit or home-hosted meal needs a separate arrangement: having a museum on the itinerary does not mean food is organised.", "Залиште час на спокійний обід. Попросіть господарів пояснити місцеві страви, склад і розмір порцій; повідомте про алергії та обмеження. Кулінарну зустріч або домашній обід домовляйте окремо: наявність музею в маршруті не означає, що харчування організоване.", "Nechte si čas na klidný oběd. Požádejte hostitele o vysvětlení místních jídel, přísad a velikosti porcí; sdělte alergie a dietní potřeby. Kulinářská návštěva či domácí oběd se domlouvá zvlášť: muzeum v programu neznamená zajištěné jídlo.") },
      { title: l("Сезон и подготовка", "Sezon și pregătire", "Season and preparation", "Сезон і підготовка", "Roční období a příprava"), body: l("Для прогулки выбирайте комфортную погоду: летом планируйте воду и тень, зимой оставляйте запас светлого времени на обратную дорогу. Перед поездкой подтвердите музей, язык, транспорт и обед. Если рассчитываете на праздник или фестиваль, проверяйте конкретную дату у организатора, а не ориентируйтесь на прошлогодний календарь.", "Alege vreme potrivită plimbărilor: vara ia apă și caută umbră, iarna păstrează lumină pentru întoarcere. Confirmă muzeul, limba, transportul și prânzul. Dacă urmărești o sărbătoare sau un festival, verifică data concretă la organizator, nu în calendarul de anul trecut.", "Choose comfortable walking weather: plan water and shade in summer and spare daylight for the return in winter. Confirm the museum, language, transport and lunch. If hoping to see a celebration or festival, check the specific date with the organiser rather than relying on last year's calendar.", "Оберіть комфортну для прогулянки погоду: влітку подбайте про воду й тінь, взимку залиште світлий час для повернення. Підтвердьте музей, мову, транспорт та обід. Якщо плануєте свято або фестиваль, уточніть дату в організатора, а не в торішньому календарі.", "Zvolte příjemné počasí pro procházku: v létě myslete na vodu a stín, v zimě na dostatek denního světla pro návrat. Potvrďte muzeum, jazyk, dopravu i oběd. Chcete-li navštívit slavnost či festival, ověřte datum u pořadatele místo loňského kalendáře.") },
    ],
  },
  soroca: {
    title: l("Сорока из Кишинёва: крепость и Днестр", "Soroca din Chișinău: cetatea și Nistrul", "Soroca from Chisinau: fortress and Dniester", "Сороки з Кишинева: фортеця та Дністер", "Z Kišiněva do Sorocy: pevnost a Dněstr"),
    description: l("Поездка в Сороку на день: крепость, прогулка у Днестра, дорога из Кишинёва, сезонные советы и проверка условий посещения.", "O zi la Soroca: cetatea, o plimbare lângă Nistru, drumul din Chișinău, recomandări de sezon și verificarea condițiilor de vizitare.", "Plan a day in Soroca: the fortress, a Dniester riverside walk, travel from Chisinau, seasonal advice and what to check before visiting.", "Поїздка до Сорок на день: фортеця, прогулянка біля Дністра, дорога з Кишинева, сезонні поради та перевірка умов відвідування.", "Den v Soroce: pevnost, procházka u Dněstru, cesta z Kišiněva, sezónní tipy a ověření podmínek návštěvy."),
    intro: l("Сорока подходит для отдельного дня на севере Молдовы. Здесь можно соединить историю крепости с прогулкой у реки. Лучше оставить место для неспешного осмотра, чем добавлять ещё одну далёкую винодельню в тот же день.", "Soroca merită o zi separată în nordul Moldovei. Combină istoria cetății cu o plimbare lângă râu. Lasă timp pentru o vizită liniștită, în loc să adaugi o vinărie îndepărtată în aceeași zi.", "Give Soroca a separate day in northern Moldova. Combine fortress history with a riverside walk. Leave room to explore at a relaxed pace instead of adding a distant winery to the same day.", "Сорокам варто присвятити окремий день на півночі Молдови. Поєднайте історію фортеці з прогулянкою біля річки. Краще залишити час на спокійний огляд, ніж додавати далеку виноробню того самого дня.", "Soroce věnujte samostatný den na severu Moldavska. Spojte historii pevnosti s procházkou u řeky. Raději si nechte čas na klidnou návštěvu než přidávat vzdálené vinařství ve stejný den."),
    stops: ["Chișinău", "Soroca", "Nistru", "Chișinău"],
    related: "gagauzia",
    sections: [
      { title: l("Крепость — главный повод приехать", "Cetatea, motivul principal al vizitei", "The fortress is the main draw", "Фортеця — головна причина приїхати", "Pevnost jako hlavní cíl"), body: l("Каменная крепость стоит у Днестра в городе Сорока. Сначала осмотрите её снаружи, затем, если доступ открыт, выделите время на внутреннее пространство. Не стройте весь день на предположении, что все уровни доступны: реставрация, погода и правила посещения могут ограничивать маршрут внутри.", "Cetatea de piatră se află lângă Nistru, în orașul Soroca. Privește-o întâi din exterior, apoi rezervă timp pentru interior, dacă accesul este permis. Nu presupune că toate nivelurile sunt accesibile: restaurarea, vremea și regulile pot limita traseul interior.", "The stone fortress stands beside the Dniester in Soroca. Look around the exterior first, then allow time inside if access is open. Do not base the day on every level being accessible: restoration, weather and visiting rules may limit the interior route.", "Кам’яна фортеця стоїть біля Дністра в місті Сороки. Спершу огляньте її зовні, а потім, якщо доступ відкритий, залиште час на внутрішній простір. Не розраховуйте на доступ до всіх рівнів: реставрація, погода й правила можуть обмежити маршрут усередині.", "Kamenná pevnost stojí u Dněstru ve městě Soroca. Nejprve si prohlédněte exteriér a potom, pokud je otevřeno, i vnitřek. Nepředpokládejte přístup na všechna podlaží: restaurování, počasí a návštěvní pravidla mohou vnitřní trasu omezit.") },
      { title: l("После крепости: река и пауза", "După cetate: râul și o pauză", "After the fortress: river and a break", "Після фортеці: річка та відпочинок", "Po pevnosti: řeka a odpočinek"), body: l("Прогулка у Днестра даёт смену темпа после осмотра. Выбирайте доступные общественные участки берега и не считайте маршрут обязательным походом: его можно сократить под погоду и силы. Обед удобнее планировать до начала обратного пути. Если путешествуете с детьми или людьми с ограниченной подвижностью, заранее уточните ступени и доступ в крепость.", "O plimbare lângă Nistru schimbă ritmul după vizită. Alege zone publice accesibile ale malului și adaptează distanța la vreme și energie. Planifică prânzul înaintea întoarcerii. Cu copii sau persoane cu mobilitate redusă, întreabă din timp despre trepte și accesul în cetate.", "A walk beside the Dniester changes the pace after sightseeing. Choose accessible public stretches of riverbank and adapt the distance to the weather and your energy. Plan lunch before starting back. With children or travellers with reduced mobility, ask ahead about steps and fortress access.", "Прогулянка біля Дністра змінює темп після огляду. Обирайте доступні громадські ділянки берега та скорочуйте відстань відповідно до погоди й сил. Обід заплануйте до повернення. Із дітьми або людьми з обмеженою рухливістю заздалегідь уточніть сходи та доступ до фортеці.", "Procházka u Dněstru změní tempo po prohlídce. Zvolte přístupné veřejné úseky břehu a délku přizpůsobte počasí a silám. Oběd naplánujte před cestou zpět. S dětmi či cestujícími s omezenou pohyblivostí předem ověřte schody a přístup do pevnosti.") },
      { title: l("День из Кишинёва: как распределить время", "O zi din Chișinău: cum împarți timpul", "A day from Chisinau: pace your visit", "День із Кишинева: як розподілити час", "Den z Kišiněva: rozvržení času"), body: l("Заложите полный день с дорогой в обе стороны. Утренний выезд оставляет больше свободы для крепости, реки и обеда, но конкретное время зависит от транспорта. Сорока — самостоятельное направление: совмещать её с Гагаузией в один день не стоит. При коротком световом дне уменьшите число остановок и заранее решите, когда возвращаться.", "Rezervă o zi întreagă cu drumul dus-întors. Plecarea dimineața lasă mai mult timp pentru cetate, râu și prânz, dar orele depind de transport. Soroca este o destinație separată: nu o combina cu Găgăuzia în aceeași zi. Când ziua este scurtă, redu opririle și stabilește întoarcerea din timp.", "Allow a full day including both journeys. A morning start leaves more flexibility for the fortress, river and lunch, but timings depend on transport. Treat Soroca as a trip in its own right; do not combine it with Gagauzia in one day. With short daylight, reduce the stops and decide your return time ahead.", "Залиште повний день із дорогою в обидва боки. Ранковий виїзд дає більше часу на фортецю, річку й обід, але години залежать від транспорту. Сороки — окремий напрямок: не поєднуйте його з Гагаузією за один день. За короткого світлового дня скоротіть зупинки й заздалегідь визначте повернення.", "Počítejte s celým dnem včetně obou cest. Ranní odjezd nechá více prostoru pro pevnost, řeku a oběd, ale časy závisejí na dopravě. Soroca je samostatný výlet; nekombinujte ji s Gagauzskem během jednoho dne. Za krátkého denního světla omezte zastávky a určete návrat předem.") },
      { title: l("Транспорт и обратная дорога", "Transportul și întoarcerea", "Transport and the return journey", "Транспорт і зворотна дорога", "Doprava a cesta zpět"), body: l("Варианты — автомобиль или общественный транспорт до Сороки. Для автомобиля заранее проложите путь и уточните место остановки рядом с крепостью. Для автобуса подтвердите у перевозчика место отправления в Кишинёве, прибытие в Сороку и обратный рейс; добавьте время на путь от остановки до крепости. Водителю отдельно сообщите, сколько остановок и ожидания планируется.", "Poți ajunge cu mașina sau transportul public până la Soroca. Cu mașina, planifică traseul și locul de oprire lângă cetate. Cu autobuzul, confirmă la transportator plecarea din Chișinău, sosirea la Soroca și cursa de întoarcere; adaugă timpul de la stație la cetate. Spune șoferului câte opriri și câtă așteptare prevezi.", "Options include a car or public transport to Soroca. For a car, plan the route and check where to stop near the fortress. For a bus, confirm the Chisinau departure point, Soroca arrival point and return service with the operator; allow time between the stop and the fortress. Tell a hired driver how many stops and how much waiting you expect.", "Варіанти — автомобіль або громадський транспорт до Сорок. Для авто прокладіть шлях і уточніть місце зупинки біля фортеці. Для автобуса підтвердьте у перевізника відправлення з Кишинева, прибуття в Сороки й зворотний рейс; додайте час від зупинки до фортеці. Водієві окремо повідомте кількість зупинок і час очікування.", "Možností je auto nebo veřejná doprava do Sorocy. Pro auto naplánujte trasu a ověřte místo zastavení u pevnosti. U autobusu potvrďte odjezdové místo v Kišiněvě, příjezd v Soroce a zpáteční spoj; připočtěte cestu ze zastávky k pevnosti. Najatému řidiči sdělte počet zastávek a očekávané čekání.") },
      { title: l("Когда ехать и что проверить", "Când să mergi și ce să verifici", "When to go and what to check", "Коли їхати й що перевірити", "Kdy jet a co ověřit"), body: l("Для открытых пространств удобна мягкая сухая погода. В жару возьмите воду и головной убор, после дождя выбирайте обувь с хорошим сцеплением, зимой учитывайте ветер у реки. До выезда проверьте актуальные часы крепости, доступные зоны, билеты и язык сопровождения. Опубликованные где-либо старые цены не используйте как подтверждённую стоимость визита.", "Vremea blândă și uscată este potrivită pentru exterior. Pe căldură ia apă și pălărie, după ploaie alege încălțăminte aderentă, iar iarna ține cont de vântul de lângă râu. Verifică orarul actual al cetății, zonele accesibile, biletele și limba ghidului. Nu trata prețurile vechi găsite online drept tarife confirmate.", "Mild, dry weather suits the outdoor parts. Bring water and a hat in heat, grippy shoes after rain and allow for riverside wind in winter. Before leaving, check current fortress hours, accessible areas, tickets and guiding language. Do not treat old prices found online as a confirmed cost for your visit.", "Для відкритих просторів зручна м’яка суха погода. У спеку візьміть воду й капелюх, після дощу — взуття з добрим зчепленням, взимку врахуйте вітер біля річки. Перевірте актуальні години фортеці, доступні зони, квитки та мову супроводу. Старі ціни в інтернеті не є підтвердженою вартістю візиту.", "Pro venkovní část se hodí mírné suché počasí. V horku vezměte vodu a klobouk, po dešti boty s dobrou podrážkou a v zimě počítejte s větrem u řeky. Ověřte aktuální otevírací dobu, přístupné části, vstupné a jazyk průvodce. Staré ceny na internetu nepovažujte za potvrzenou cenu návštěvy.") },
    ],
  },
};
